okta:
  oauth2:
    issuer: https://dev-82466008.okta.com/oauth2/default
    client-id: 0oa4wirfgcN49VgSd5d7
    client-secret: QrBx10GGmsTgkXNK3VOJyH0_7-6KJhoivak0aCoE
spring:
    thymeleaf:
      cache: false
